### ISSUE TITLE
Very big header on gtk4 nautilus.

### ISSUE THREAD

**Issue by arun54321** [vinceliuice/Nephrite-gtk-theme#4]
![image](https://user-images.githubusercontent.com/42943340/187342783-cf245b72-1fe5-42cf-966a-333b4434d64f.png)

**Comment by vinceliuice** [comment]
How to get gtk4 version nautilus ？

**Comment by nguyensang28** [comment]
I think you can try this and get nautilus nightly (gtk4) from the instructions below since I see that you uses Manjaro https://wiki.gnome.org/Apps/Nightly

**Comment by vinceliuice** [comment]
OK, I'll try it

**Comment by arun54321** [comment]
> How to get gtk4 version nautilus ？

You can get gtk4 Nautilus on Fedora 37 too.
